# Generated by Django 4.1 on 2022-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
